import Head from "next/head";

import MyMovies from "@/components/common/Movies/MyMovies";
import AuthGuard from "@/components/common/AuthGuard/AuthGuard";

export default function Home() {
  return (
    <>
      <Head>
        <title>Movies App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MyMovies />
    </>
  );
}
